name: Publish zip to release

on:
  release:
    types:
    - published
    branches:
    - main

jobs:
  createZip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Zip files
      run: 'zip -r CCVanillaUI-${{ github.event.release.tag_name }}.zip z_cosmetics/'
    - name: Upload zip to release
      uses: AButler/upload-release-assets@v3
      with:
        files: 'CCVanillaUI-${{ github.event.release.tag_name }}.zip'
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
